#!/bin/bash
container_loc="/opt/docker/razor/"
c_backups_loc="${container_loc}/backup"

container=db_razor
mysql_user=root
mysql_pass=dsg43t2e
mysql_db=razor

minio_access_key='BNyoD'
minio_secret_key='2uKmaVsZ'

LOGFILE=${c_backups_loc}/razor_db.log
DATE=$(date +%Y-%m-%d_%H.%M)

_PROJECT="Razor Notes Baza"

echo "$(date '+%Y%m%d %T') : Backup the ${_PROJECT} DB" | tee -a ${LOGFILE}


docker container exec -i ${container} mysqldump --user="${mysql_user}" --password="${mysql_pass}" ${mysql_db} > ${c_backups_loc}/${mysql_db}.sql 2>> ${LOGFILE}

if [ $? -eq 0 ]; then
    echo "Backup of the database successfull" | tee -a ${LOGFILE}
    mkdir -p ${c_backups_loc}/old
    find ${c_backups_loc}/old -mtime 10 -name "*.sql" -delete
    cp ${c_backups_loc}/${mysql_db}.sql ${c_backups_loc}/old/${mysql_db}_${DATE}.sql 2>> ${LOGFILE}
    #python3 ${c_backups_loc}/mc_upload.py ${minio_access_key} ${minio_secret_key}
    docker run --rm -it --entrypoint=/bin/sh -v ${c_backups_loc}/old/${mysql_db}_${DATE}.sql:/${mysql_db}_${DATE}.sql minio/mc -c "mc alias set --insecure myminio https://box02.razor.si ${minio_access_key} ${minio_secret_key} && mc --insecure cp ${mysql_db}_${DATE}.sql myminio/razorbucket/razor_notes/"

else
    echo "Backup of the database Failed" | tee -a ${LOGFILE}
fi
echo "$(date '+%Y%m%d %T') : FINISHED the ${_PROJECT} Backup" | tee -a ${LOGFILE}
